=== Victoria535/epam_traine/lab-3/lab_3/greenhouses.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema" targetNamespace="http://www.example.org/greenhouses"
        elementFormDefault="qualified">
    <element name="greenhouses">
        <complexType>
            <sequence>
                <element name="greenhouse" maxOccurs="unbounded">
                    <complexType>
                        <sequence>
                            <element name="name" type="string"/>
                            <element name="soil">
                                <simpleType>
                                    <restriction base="string">
                                        <enumeration value="GROUND"/>
                                        <enumeration value="PODZOLIC"/>
                                        <enumeration value="SOD_PODZOLIC"/>
                                    </restriction>
                                </simpleType>
                            </element>
                            <element name="origin" type="string"/>
                            <element name="visual-parameters">
                                <complexType>
                                    <sequence>
                                        <element name="colorStem" type="string"/>
                                        <element name="colorLeaf" type="string"/>
                                        <element name="mediumSize" type="positiveInteger"/>
                                    </sequence>
                                </complexType>
                            </element>
                            <element name="growing-tips">
                                <complexType>
                                    <sequence>
                                        <element name="temperature" type="integer"/>
                                        <element name="lighting" type="boolean"/>
                                        <element name="watering">
                                            <simpleType>
                                                <restriction base="integer">
                                                    <minInclusive value="10"/>
                                                    <maxInclusive value="500"/>
                                                </restriction>
                                            </simpleType>
                                        </element>
                                    </sequence>
                                </complexType>
                            </element>
                            <element name="multiplying">
                                <simpleType>
                                    <restriction base="string">
                                        <enumeration value="SEEDS"/>
                                        <enumeration value="LEAVES"/>
                                        <enumeration value="CUTTINGS"/>
                                    </restriction>
                                </simpleType>
                            </element>
                        </sequence>
                        <attribute name="id" type="string" use="required"/>
                    </complexType>
                </element>
            </sequence>
        </complexType>
    </element>
</schema>

=== Victoria535/epam_traine/lab-3/lab_3/greenhouses.xml
<?xml version="1.0" encoding="UTF-8"?>
<greenhouses xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
             xmlns="http://www.example.org/greenhouses"
             xsi:schemaLocation="http://www.example.org/greenhouses greenhouses.xsd">


    <greenhouse id="1">
        <name>Tulip</name>
        <soil>GROUND</soil>
        <origin>Europe</origin>
        <visual-parameters>
            <colorStem>orange</colorStem>
            <colorLeaf>red</colorLeaf>
            <mediumSize>30</mediumSize>
        </visual-parameters>
        <growing-tips>
            <temperature>22</temperature>
            <lighting>true</lighting>
            <watering>200</watering>
        </growing-tips>
        <multiplying>SEEDS</multiplying>
    </greenhouse>
    <greenhouse id="2">
        <name>Lily</name>
        <soil>PODZOLIC</soil>
        <origin>Europe</origin>
        <visual-parameters>
            <colorStem>white</colorStem>
            <colorLeaf>white</colorLeaf>
            <mediumSize>45</mediumSize>
        </visual-parameters>
        <growing-tips>
            <temperature>16</temperature>
            <lighting>true</lighting>
            <watering>300</watering>
        </growing-tips>
        <multiplying>LEAVES</multiplying>
    </greenhouse>
    <greenhouse id="3">
        <name>Clove</name>
        <soil>SOD_PODZOLIC</soil>
        <origin>Asia</origin>
        <visual-parameters>
            <colorStem>green</colorStem>
            <colorLeaf>yellow</colorLeaf>
            <mediumSize>60</mediumSize>
        </visual-parameters>
        <growing-tips>
            <temperature>14</temperature>
            <lighting>true</lighting>
            <watering>150</watering>
        </growing-tips>
        <multiplying>CUTTINGS</multiplying>
    </greenhouse>
</greenhouses>
